_PBuilder.init({
	'header':{							
		'default_component':'header',
		'extended_default_component':true,
		'dragdrop':true,
		'remove':true,
		'edit_this':true,
		'new':true
	},
	'header-pin':{
		'default_component':'article',
		'extended_default_component':true,
		'dragdrop':true,
		'remove':true,
		'edit_this':true,
		'new':true
	},
	'content':{
		'default_component':'article',
		'extended_default_component':true,
		'dragdrop':true,
		'remove':true,
		'edit_this':true,
		'new':true
	},
	'second-promo':{
		'default_component':'header',
		'extended_default_component':true,
		'dragdrop':true,
		'remove':true,
		'edit_this':true,
		'new':true
	},
	'footer':{
		'default_component':'article',
		'extended_default_component':true
	}
});