_PBuilder.init({
	'properties':{
		'site_title':'Relu person',
		'components_path':'ArthurWellesleyCSSconcept/'
	},
	'schema':{
		's1':{							
			'default_component':'block-img-title-content',
			'extended_default_component':true,
			'dragdrop':true,
			'remove':true,
			'edit_this':true,
			'new':true
		},
		's2':{
			'default_component':'block-title-h2',
			'extended_default_component':true,
			'dragdrop':true,
			'remove':true,
			'edit_this':true,
			'new':true
		},
		's3':{
			'default_component':'block-img',
			'extended_default_component':true,
			'dragdrop':true,
			'remove':true,
			'edit_this':true,
			'new':true
		},
		's4':{
			'default_component':'block-img',
			'extended_default_component':true,
			'dragdrop':true,
			'remove':true,
			'edit_this':true,
			'new':true
		},
		's5':{
			'default_component':'block-img-title-content',
			'extended_default_component':true,
			'dragdrop':true,
			'remove':true,
			'edit_this':true,
			'new':true
		},
		's6':{
			'default_component':'block-title-content',
			'extended_default_component':true,
			'dragdrop':true,
			'remove':true,
			'edit_this':true,
			'new':true
		},
		's7':{
			'default_component':'block-img',
			'extended_default_component':true,
			'dragdrop':true,
			'remove':true,
			'edit_this':true,
			'new':true
		}
	}
});